paths :
  chv_extbroker : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/pubsub_broker/bin; sudo ./extbroker"
  uev_localpubsub : "cd /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/pubsub_local/bin; sudo ./localPubSub"
  ran_localpubsub : "cd /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/pubsub_local/bin; sudo ./localPubSub"
  gnb_cu : "cd /opt/netprizm2/network/ran/fr1/cu1/scripts; sudo ./run.sh -r 1"
  ran_csm : "cd /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/csm/bin; sudo ./csm"
  uev_csm : "cd /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/csm/bin; sudo ./csm"
  ran_ranp : "cd /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/ranp/bin; sudo ./ranp"
  uev_uemp : "cd /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/uemp/bin; sudo ./uemp 1 0"
  gnb_du : "cd /opt/netprizm2/network/ran/fr1/du11/scripts; sudo ./run.sh -r 1"
  chv_localpubsub : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/pubsub_local/bin; sudo ./localPubSub"
  chv_csm : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/csm/bin; sudo ./csm"
  chv_chv : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/chv/bin;sudo ./chv 17 18 19 20 21 22 23"

sitpath:
  ran_extbroker : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/pubsub/extBroker/build/; sudo ./extbroker"
  uev_localpubsub : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/pubsub/localPubSub/build; sudo ./localPubSub"
  ran_localpubsub : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/pubsub/localPubSub/build; sudo ./localPubSub"
  gnb_cu : "cd /opt/netprizm2/network/ran/fr1/cu1/scripts; sudo ./run.sh -r 1"
  ran_csm : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/csm/build; sudo ./csm"
  uev_csm : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/csm/build; sudo ./csm"
  ran_ranp : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/ranp/build; sudo ./ranp"
  uev_uemp : "cd /home/amtvphy/dev_jan19/amantya/5G/VPHY/uemp/build; sudo ./uemp 1 0"
  gnb_du : "cd /opt/netprizm2/network/ran/fr1/du11/scripts; sudo ./run.sh -r 1"
  chv_localpubsub : ""
  chv_csm : ""
  chv_chv : ""



cleancommad:
  pkill : "sudo pkill -SIGKILL pubsub;sudo pkill -SIGKILL csm;sudo pkill -SIGKILL xv_stub;sudo pkill -SIGKILL ue;sudo pkill -SIGKILL ran;sudo pkill -SIGKILL extb;sudo pkill -SIGKILL localP;sudo rm -rf /dev/hugepages/* /dev/shm/* /tmp/pubsub* /var/run/dpdk/*;ulimit -c unlimited"


credentials :
  password : "Shiv@123456#"
  username : "singhsh2"
  ran_ips : ["10.20.249.3","10.20.249.4"]
  ue_ips : ["10.20.249.5","10.20.249.6","10.20.249.7","10.20.249.8","10.20.249.9","10.20.249.10"]
  cu_ip : "10.20.249.2"
  chv_ip : ["10.20.249.12"]

sitcredential:
  password : "0pal1"
  username : "amtsit"
  ran_ips : ["10.20.249.18","10.20.249.19","10.20.249.20"]
  ue_ips : ["10.20.249.22","10.20.249.24","10.20.249.26","10.20.249.28","10.20.249.29","10.20.249.33"]
  cu_ip : "10.20.249.17"
  chv_ip : ["10.20.249.25","10.20.249.32"]


UEs:
  Ue_ip_1 :  "10.20.249.6"
  Ue_ip_2 :  "10.20.249.7"
  Ue_ip_3 :  "10.20.249.8"
  Ue_ip_4 :  "10.20.249.9"
  Ue_ip_5 :  "10.20.249.10"


sitUE :
  Ue_ip_1 :  "10.20.249.22"
  Ue_ip_2 :  "10.20.249.24"
  Ue_ip_3 :  "10.20.249.26"
  Ue_ip_4 :  "10.20.249.28"
  Ue_ip_5 :  "10.20.249.29"
  Ue_ip_6 :  "10.20.249.33"
  

modules:
  ranmodule : ["localPubSub","csm","ranp","gnb_du"]
  uemodule : ["localPubSub","csm","uemp"]
  cumodule : ["gnb_cu"]
  chvmodule : ["extbroker","localPubSub","csm","chv"]


corecommads :
  chv_extbroker : "ls /opt/netprizm2/network/v23.1.3.2.1.vzw/pubsub_broker/bin/ | grep core"
  uev_localpubsub : "ls /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/pubsub_local/bin/ |  grep core"
  ran_localpubsub : "ls /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/pubsub_local/bin/ | grep core"
  gnb_cu : "ls /opt/netprizm2/network/ran/fr1/cu1/scripts/ | grep core"
  ran_csm : "ls /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/csm/bin/ | grep core "
  uev_csm : "ls /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/csm/bin/ | grep core"
  ran_ranp : "ls /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/ranp/bin/ | grep core"
  uev_uemp : "ls /home/singhsh2@Netprizm.local/Neelam/vphy.v23.5.1.0/uemp/bin | grep core"
  gnb_du : "ls /opt/netprizm2/network/ran/fr1/du11/scripts/| grep core"
  chv_localpubsub : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/pubsub_local/bin/ | grep core"
  chv_csm : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/csm/bin/ | grep core"
  chv_chv : "cd /opt/netprizm2/network/v23.1.3.2.1.vzw/chv/bin/ | grep core"

sitcorecommands:
  ran_extbroker : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/pubsub/extBroker/build/ | grep core"
  uev_localpubsub : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/pubsub/localPubSub/build/ |  grep core"
  ran_localpubsub : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/pubsub/localPubSub/build/ | grep core"
  gnb_cu : "ls /opt/netprizm2/network/ran/fr1/cu1/scripts/ | grep core"
  ran_csm : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/csm/build/ | grep core "
  uev_csm : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/csm/build/ | grep core"
  ran_ranp : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/ranp/build/ | grep core"
  uev_uemp : "ls /home/amtvphy/dev_jan19/amantya/5G/VPHY/uemp/build/ | grep core"
  gnb_du : "ls /opt/netprizm2/network/ran/fr1/du11/scripts/| grep core"
  chv_localpubsub : ""
  chv_csm : ""
  chv_chv : ""

